// ALL USERS
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

// USER THAT SELECTED
export const FETCH_SELECTED_REQUEST = "FETCH_SELECTED_REQUEST";
export const FETCH_SELECTED_SUCCESS = "FETCH_SELECTED_SUCCESS";
export const FETCH_SELECTED_FAILURE = "FETCH_SELECTED_FAILURE";

// POSTS
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
